sudo: required

language: python

python:
- "3.5"
- "3.6"

branches:
  only:
    - master

install:
    - sudo apt-get install python-pip
    - pip install -r requirements.txt
    - sudo apt-get update
    - wget --no-check-certificate https://github.com/ideawu/ssdb/archive/master.zip
    - unzip master
    - cd ssdb-master
    - make
    - sudo make install
    - cd /usr/local/ssdb
    - sudo ./ssdb-server -d ssdb.conf

script: pytest