language: python

python:
- "3.5"
- "3.6"

branches:
  only:
    - master

env:
    global:
        - SSDB=./ssdb-server

install:
    - wget https://github.com/ideawu/ssdb/archive/master.zip
    - unzip master
    - make -C ssdb-master
    - mv ssdb-master/{ssdb-server,ssdb.conf} ./
    - pip install -r requirements.txt

before_script:
  - ./ssdb-server ssdb.conf -d

after_script:
  - killall -w ssdb-server
  - rm -rf ssdb-master/var/*

script: pytest